version: "3.8"
services: 
    larabook_server:
        image: nginx:stable-alpine
        ports: 
            - 80:80
        volumes: 
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on: 
            - larabook_api 
    larabook_api:
        build:
            context: ./dockerfiles
            dockerfile: larabook_api.Dockerfile
        volumes: 
            - ./:/var/www/larabook_api 